# Dockerfile.base
FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

# Install all dependencies only once
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app during actual build in specific Dockerfiles
